Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -186,24 +186,33 @@ jobs:
           echo ""
           echo "KernelSU Next configuration step completed."
 
+      # ==========================================
+      # BUILD KERNEL
+      # ==========================================
       - name: Build Kernel
         working-directory: kernel
+        shell: bash
         run: |
-          set -e
+         set -o pipefail
 
-          echo "========================================"
-          echo "             BUILD KERNEL"
-          echo "========================================"
+         echo "=========================================="
+         echo "           BUILD KERNEL"
+         echo "=========================================="
 
-          test -f "$BUILD_DIR/.config" || {
-            echo "ERROR: $BUILD_DIR/.config tidak ditemukan!"
-            exit 1
-          }
+         make -C "$BUILD_DIR" \
+         O="$BUILD_DIR" \
+         ARCH=arm64 \
+         CROSS_COMPILE="$CROSS_COMPILE" \
+         -j"$(nproc)" 2>&1 | tee "$GITHUB_WORKSPACE/build.log"
 
-          make -j"$(nproc)" \
-            O="$BUILD_DIR" \
-            ARCH=arm64 \
-            "$@"
+         echo ""
+         echo "=========================================="
+         echo "        BUILD ERROR SUMMARY"
+         echo "=========================================="
+  
+         grep -nEi \
+         'error:|fatal error:|undefined reference|No such file|No rule to make|Error [0-9]+|sub-makel' \
+         "$GITHUB_WORKSPACE/build.log" | tail -100 || true
           
       # ==========================================
       # 8. FIND KERNEL IMAGE
